import argparse
import math
import matplotlib.pyplot as plt


def draw_square(ax, x, y, size, angle):
    x2 = x + size * math.cos(angle)
    y2 = y + size * math.sin(angle)
    ax.plot([x, x2], [y, y2], color="#a83939", linewidth=1)
    return (x2, y2), (x2, y2)


def pythagoras(ax, x, y, size, angle, depth):
    if depth == 0 or size < 1e-3:
        return
    c_right, c_left = draw_square(ax, x, y, size, angle)
    new_size = size / math.sqrt(2)
    pythagoras(ax, c_left[0], c_left[1], new_size, angle + math.pi / 4, depth - 1)
    pythagoras(ax, c_right[0], c_right[1], new_size, angle - math.pi / 4, depth - 1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--depth", type=int, default=10)
    parser.add_argument("--size", type=float, default=1.0)
    args = parser.parse_args()

    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_aspect("equal")
    pythagoras(ax, x=0.0, y=0.0, size=args.size, angle=math.pi / 2, depth=args.depth)
    ax.autoscale_view()
    ax.axis("off")
    plt.show()
    print("Conclusion: the figure is generated by recursive branching with constant angle split and length scaling.")


if __name__ == "__main__":
    main()
