import argparse
import math
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon

def draw_square(ax, x, y, size, angle):
    c = math.cos(angle)
    s = math.sin(angle)
    corners = [
        (x, y),
        (x + size * c, y + size * s),
        (x + size * c - size * s, y + size * s + size * c),
        (x - size * s, y + size * c)
    ]
    poly = Polygon(corners, closed=True, edgecolor="black", facecolor="#A7C7E7", linewidth=0.5)
    ax.add_patch(poly)
    return corners[2], corners[3]

def pythagoras(ax, x, y, size, angle, depth):
    if depth == 0 or size < 1e-3:
        return
    c_right, c_left = draw_square(ax, x, y, size, angle)
    new_size = size / math.sqrt(2)
    pythagoras(ax, c_left[0], c_left[1], new_size, angle + math.pi/4, depth - 1)
    pythagoras(ax, c_right[0], c_right[1], new_size, angle - math.pi/4, depth - 1)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--depth", type=int, default=8)
    parser.add_argument("--size", type=float, default=1.0)
    args = parser.parse_args()

    fig, ax = plt.subplots(figsize=(8,8))
    ax.set_aspect("equal")
    pythagoras(ax, x=0.0, y=0.0, size=args.size, angle=0.0, depth=args.depth)
    ax.autoscale_view()
    ax.axis("off")
    plt.title(f"Pythagoras tree, depth={args.depth}")
    plt.show()
    print("Conclusion: the fractal is generated by recursive placement of two smaller squares rotated around the parent square.")

if __name__ == "__main__":
    main()
